COMFYUI_IMAGE_GENERATION_ACTION_LABEL = "image generation"
PUBLISHING_ACTION_LABEL = "publishing"
PUBLISHING_TARGET_LABEL = "publish target"


__all__ = [
    "COMFYUI_IMAGE_GENERATION_ACTION_LABEL",
    "PUBLISHING_ACTION_LABEL",
    "PUBLISHING_TARGET_LABEL",
]
