from __future__ import annotations


MOCK_AGENT_KNOWLEDGE = "knowledge"
MOCK_AGENT_IMAGE_PLANNER = "image_planner"
MOCK_AGENT_CRITIC_CURATOR = "critic_curator"

MOCK_AGENT_NAMES: tuple[str, ...] = (
    MOCK_AGENT_KNOWLEDGE,
    MOCK_AGENT_IMAGE_PLANNER,
    MOCK_AGENT_CRITIC_CURATOR,
)

MOCK_ARTIFACT_CONTEXT_NOTE = "context_note"
MOCK_ARTIFACT_IMAGE_PLAN = "image_plan"
MOCK_ARTIFACT_REVIEW_CHECKLIST = "review_checklist"

MOCK_ARTIFACT_TYPES: tuple[str, ...] = (
    MOCK_ARTIFACT_CONTEXT_NOTE,
    MOCK_ARTIFACT_IMAGE_PLAN,
    MOCK_ARTIFACT_REVIEW_CHECKLIST,
)


__all__ = [
    "MOCK_AGENT_CRITIC_CURATOR",
    "MOCK_AGENT_IMAGE_PLANNER",
    "MOCK_AGENT_KNOWLEDGE",
    "MOCK_AGENT_NAMES",
    "MOCK_ARTIFACT_CONTEXT_NOTE",
    "MOCK_ARTIFACT_IMAGE_PLAN",
    "MOCK_ARTIFACT_REVIEW_CHECKLIST",
    "MOCK_ARTIFACT_TYPES",
]
