DEFAULT_REQUEST_METADATA_WORKSPACE = "ai-artist-main"
DEFAULT_REQUEST_METADATA_AGENT = "ai-artist-main"
DEFAULT_REQUEST_CHANNEL = "cli"

REQUEST_TEXT_FIELD = "request_text"
REQUESTER_SCOPE_FIELD = "requester_scope"
POLICY_SCOPE_FIELD = "policy_scope"
REQUEST_CHANNEL_FIELD = "channel"
REQUEST_METADATA_WORKSPACE_FIELD = "workspace"
REQUEST_METADATA_AGENT_FIELD = "agent"
REQUEST_FINGERPRINT_FIELD = "request_fingerprint"


__all__ = [
    "DEFAULT_REQUEST_CHANNEL",
    "DEFAULT_REQUEST_METADATA_AGENT",
    "DEFAULT_REQUEST_METADATA_WORKSPACE",
    "POLICY_SCOPE_FIELD",
    "REQUESTER_SCOPE_FIELD",
    "REQUEST_CHANNEL_FIELD",
    "REQUEST_FINGERPRINT_FIELD",
    "REQUEST_METADATA_AGENT_FIELD",
    "REQUEST_METADATA_WORKSPACE_FIELD",
    "REQUEST_TEXT_FIELD",
]
