DEFAULT_REQUESTER_SCOPE = "local-user"
DEFAULT_POLICY_SCOPE = "default"
DEFAULT_PUBLISHING_ACTOR_SCOPE = "user:local"
DEFAULT_PUBLISHING_POLICY_SCOPE = "workspace:ai-artist-main"


__all__ = [
    "DEFAULT_POLICY_SCOPE",
    "DEFAULT_PUBLISHING_ACTOR_SCOPE",
    "DEFAULT_PUBLISHING_POLICY_SCOPE",
    "DEFAULT_REQUESTER_SCOPE",
]
