OPERATION_FIELD = "operation"
TARGET_FIELD = "target"
TASK_ID_FIELD = "task_id"
REQUEST_ID_FIELD = "request_id"
EXECUTION_ENVELOPE_ID_FIELD = "execution_envelope_id"
CLIENT_RESPONSE_FIELD = "client_response"
CORRELATION_ID_FIELD = "correlation_id"
REQUEST_KIND_FIELD = "request_kind"
REQUESTER_SCOPE_FIELD = "requester_scope"
POLICY_SCOPE_FIELD = "policy_scope"
ALLOW_FIELD = "allow"
STATUS_FIELD = "status"
REQUIRES_HUMAN_APPROVAL_FIELD = "requires_human_approval"
REASON_FIELD = "reason"
POLICY_VERSION_FIELD = "policy_version"


__all__ = [
    "ALLOW_FIELD",
    "CLIENT_RESPONSE_FIELD",
    "CORRELATION_ID_FIELD",
    "EXECUTION_ENVELOPE_ID_FIELD",
    "OPERATION_FIELD",
    "POLICY_SCOPE_FIELD",
    "POLICY_VERSION_FIELD",
    "REASON_FIELD",
    "REQUEST_ID_FIELD",
    "REQUESTER_SCOPE_FIELD",
    "REQUEST_KIND_FIELD",
    "REQUIRES_HUMAN_APPROVAL_FIELD",
    "STATUS_FIELD",
    "TASK_ID_FIELD",
    "TARGET_FIELD",
]
