from backend.audit_contracts import AUDIT_ACTOR_SCOPE_FIELD, AUDIT_POLICY_SCOPE_FIELD


SIDE_EFFECT_ACTOR_SCOPE_FIELD = AUDIT_ACTOR_SCOPE_FIELD
SIDE_EFFECT_POLICY_SCOPE_FIELD = AUDIT_POLICY_SCOPE_FIELD
SIDE_EFFECT_OPERATION_FIELD = "operation"
SIDE_EFFECT_TARGET_FIELD = "target"
SIDE_EFFECT_STATUS_FIELD = "status"
SIDE_EFFECT_REASON_FIELD = "reason"
SIDE_EFFECT_EXECUTION_ENVELOPE_ID_FIELD = "execution_envelope_id"
SIDE_EFFECT_CLIENT_RESPONSE_FIELD = "client_response"


__all__ = [
    "SIDE_EFFECT_ACTOR_SCOPE_FIELD",
    "SIDE_EFFECT_CLIENT_RESPONSE_FIELD",
    "SIDE_EFFECT_EXECUTION_ENVELOPE_ID_FIELD",
    "SIDE_EFFECT_OPERATION_FIELD",
    "SIDE_EFFECT_POLICY_SCOPE_FIELD",
    "SIDE_EFFECT_REASON_FIELD",
    "SIDE_EFFECT_STATUS_FIELD",
    "SIDE_EFFECT_TARGET_FIELD",
]
