from __future__ import annotations


DEFAULT_SOURCE_FRESHNESS_ALL_REQUIRED_SOURCES_UNCHANGED = True
DEFAULT_SOURCE_FRESHNESS_CHANGED_SOURCE_COUNT = 0


__all__ = [
    "DEFAULT_SOURCE_FRESHNESS_ALL_REQUIRED_SOURCES_UNCHANGED",
    "DEFAULT_SOURCE_FRESHNESS_CHANGED_SOURCE_COUNT",
]
